### ISSUE TITLE
Implement timeout

### ISSUE THREAD

**Issue by plessl** [plessl/wkpdf#1]
Terminate wkpdf after an optional, user defined timeout to prevent wkpdf from hanging with resources are not available etc.

**Comment by jwlrs** [comment]
So is the --timeout option shown in help just a placeholder?  I would agree, this is very important!

**Comment by plessl** [comment]
No, the timeout option is not merely a placeholder, but should work. I'm pretty confident that the option worked before, but since wkpdf is broken on OS X Lion and I still didn't find a way to fix it, I'm not able to do any tests.

**Comment by jwlrs** [comment]
Any thoughts on if you (or someone else involved n the project?) will be able to fix the Lion issue in the near future?  If I knew anything about Ruby and webkit underpinnings, I'd take it on myself...

**Comment by plessl** [comment]
Unfortunately, I have been pretty busy and didn't have time to investigate the problem in more detail. I have some idea what causes the problem: the problem is related to pagination. If you run wkpdf with --paginate no, then wkpdf works also in OS X Lion.

The good news is, that I will have vacation next week and I think I will find some time to spend on wkpdf. My current plans are as follows:
- release an updated wkpdf version that disables --paginate (at least on Lion)
- debug the --timeout option
  - look for ways to re-enable pagination in Lion

**Comment by jwlrs** [comment]
That is great to hear, hope you can find the time (and get some relaxing done too!).

**Comment by plessl** [comment]
Has been fixed with #29.
