### ISSUE TITLE
Ampersand when printing URL

### ISSUE THREAD

**Issue by Cadrach** [plessl/wkpdf#12]
When using an URL as --source, if an ampersand (&) is present in the URL, it will be parsed and the remaining parameters (and command line options) will be interpreted as a new command.

I tried unsuccessfully to escape the URL with ' or ", using $a or ^& does not work either. Even setting a variable and using it as source (for example --source $myurl) generates the error.

Example command: wkpdf --output test.pdf --source "http://google.com?param1=1&param2=2"
This happens on Mac OS Server 10.5.8
wkpdf 0.3.5 (0.3.7 breaks on 10.5.8: http://github.com/plessl/wkpdf/issues/#issue/11)

**Comment by plessl** [comment]
This is a shell problem rather than a wkpdf problem. In bash you need to properly escape the ampersand using \&. I was looking for a more elegant solution to quote the whole URL too, but didn't find a solution.

**Comment by jonathanstark** [comment]
I can't seem to get URLs that contain ampersands working. Can someone give a quick example?

TIA!
j

**Comment by plessl** [comment]
You need to quote the ampersand with a backslash (\&param=foo).
