### ISSUE TITLE
NSURLErrorDomain

### ISSUE THREAD

**Issue by davethewave** [plessl/wkpdf#13]
When wkpdf encounters some long href url in a page, it exit with 
<WebView: 0x1033c20e0> didFailProvisionalLoadWithError "The operation couldn’t be completed. (NSURLErrorDomain error -999.)",
try it with
wkpdf --source http://www.asylumitalia.it/ --stylesheet-media screen --print-background yes --format A4 --portrait --output test.pdf --debug
thanks

**Comment by plessl** [comment]
This problem has not been reproduced/reported by others. Close issue.

**Comment by John07** [comment]
I'm running into the same issue right now on multiple pages. (I'm on Snow Leopard 10.6.8)

```
wkpdf --source "http://www.fastcodesign.com/1669869/a-champion-racing-yacht-designer-chasing-perfection" --output yacht.pdf --debug
```

Here's a gist with the last few lines of the debug log: https://gist.github.com/3782405

Similar error also on e.g.

```
wkpdf --source "http://www.theatlantic.com/magazine/archive/2012/05/american-mozart/8931/?single_page=true" --output kanye.pdf --debug
```

**Comment by plessl** [comment]
Thanks for the test cases. The same problem exists on 10.7.x too. I will reopen this report, though I currently don't have time to look into the problem myself. An initial search revealed that it might be safe to ignore this error (https://discussions.apple.com/thread/1727260?start=0&tstart=0).

**Comment by John07** [comment]
Okay, let me know if you need more test cases or someone testing a bug fix.
Even with this bug occasionally occurring, wkpdf has been of great use for me, so thanks a lot for making it available to everyone and even keeping it up-to-date!

**Comment by plessl** [comment]
I have just release an updated version 0.6.8 of wkpdf which provides a solution for the reported problem.

The solution is to use the `--ignore-http-errors` command line flag. This flag was already present in previous versions but did not suppress all resource loading errors. Now errors that are covered have been extended, such that it should work for your test cases. The changes have also revealed some bugs with the previous implementation, such it was worth the effort twice.

**Comment by John07** [comment]
Awesome, thank you! Works perfectly.
