### ISSUE TITLE
OS X 10.7 error on first test

### ISSUE THREAD

**Issue by thekrynn** [plessl/wkpdf#19]
Installed and ran the first test command: wkpdf --source http://www.apple.com --output apple.pdf
Received the following error:

sh-3.2# sudo wkpdf --source http://www.apple.com --output apple.pdf
2011-08-03 04:51:51.397 ruby[63461:a07] **\* Assertion failure in -[WebHTMLView lockFocusIfCanDraw], /SourceCache/AppKit/AppKit-1138/AppKit.subproj/NSView.m:6068
2011-08-03 04:51:51.398 ruby[63461:a07] lockFocus sent to a view which is not in a window
2011-08-03 04:51:51.402 ruby[63461:a07](0   CoreFoundation                      0x00007fff8c941986 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff97ba4d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8c9417ba +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x00007fff950ae14f -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 169
    4   AppKit                              0x00007fff934d899e -[NSView lockFocusIfCanDraw] + 515
    5   AppKit                              0x00007fff934d86b7 -[NSView lockFocus] + 39
    6   AppKit                              0x00007fff934d627b -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 3780
    7   AppKit                              0x00007fff934cf093 -[NSView displayIfNeeded] + 1676
    8   WebKit                              0x00007fff8eba6a84 -[WebHTMLView knowsPageRange:] + 36
    9   AppKit                              0x00007fff93b6ec72 -[NSView%28NSPrinting2%29 _knowsPagesFirst:last:] + 164
    10  AppKit                              0x00007fff9399b161 -[NSConcretePrintOperation%28NSInternal%29 _validatePagination] + 179
    11  AppKit                              0x00007fff9399b2af -[NSConcretePrintOperation%28NSInternal%29 _firstPageNumber] + 27
    12  AppKit                              0x00007fff9399b352 -[NSConcretePrintOperation%28NSInternal%29 _validateJobPageNumbers] + 54
    13  AppKit                              0x00007fff9399b69e -[NSConcretePrintOperation%28NSInternal%29 _firstRenderPageNumber] + 27
    14  AppKit                              0x00007fff93be0bf1 -[NSView%28NSPrintingInternal%29 _printForCurrentOperation] + 85
    15  AppKit                              0x00007fff939999c5 -[NSConcretePrintOperation _renderView] + 224
    16  AppKit                              0x00007fff939993e1 -[NSConcretePrintOperation runOperation] + 363
    17  libffi.dylib                        0x00007fff940b1e7c ffi_call_unix64 + 76
    18  ???                                 0x00007fff66c49d40 0x0 + 140734917549376)

**Comment by plessl** [comment]
Unfortunately the OX 10.7. update breaks wkpdf.

I spent some time investigating the problem, but couldn't neither find the source of the problem nor a workaround. It might even be the case that the problem is caused by a bug in AppKit.

Any hint and idea how to track down the problem would be greatly appreciated.
