### ISSUE TITLE
Convert internal anchors <href="#.."> to internal pdf links

### ISSUE THREAD

**Issue by jmoiron** [plessl/wkpdf#20]
It would be nice if anchors that are internal to a document (like in a TOC for instance) could jump to other places in the document rather than be hypertext links to the original HTML document instead.

**Comment by plessl** [comment]
That sounds useful though I'm not sure this is possible with the current way wkpdf is implemented. wkpdf uses the WebKit framework and uses Cocoa built-in printing functionality. I'm not sure whether there is any way to customize the generated PDF.

**Comment by ralphtq** [comment]
I would also like this feature

**Comment by plessl** [comment]
Closing this feature request since I don't see a way how to implement this with WebKit.

**Comment by iandennismiller** [comment]
Is it possible to push this request upstream to the WebKit folks?

I don't know where WebKit would need to be modified in order to support internal links, but it sounds like a feature they should support, doesn't it?

**Comment by plessl** [comment]
Yes, this sounds like a feature that would actually be quite useful. However, I have no personal connections with any WebKit developer.

If you are interested in this features, feel free to file a feature request with WebKit.
