### ISSUE TITLE
SVG dropshadow filter not rendered

### ISSUE THREAD

**Issue by nilsm** [plessl/wkpdf#26]
**version:** wkpdf 0.6.1

To replicate:
1. Create an HTML file with inline SVG content with a dropshadow (see below for example).
2. Run wkpdf.

**expected:** Faithfully rendered graphic in PDF.
**result:** The actual shape is rendered correctly in the PDF but the dropshadow is omitted.

SVG sample:

https://gist.github.com/1994389

**Comment by nilsm** [comment]
Note: css box-shadow property is rendered correctly, so it may be possible to workaround in some instances.

**Comment by plessl** [comment]
Please add an example of the complete HTML document with the inline SVG.

**Comment by nilsm** [comment]
I'm actually getting no output from inline SVG on my laptop, will try again from office computer next week. Think there is a version mismatch.

**Comment by plessl** [comment]
Closed since no code for reproducing the issue was provided.
