### ISSUE TITLE
--save-delay appears to not work

### ISSUE THREAD

**Issue by anoopsinha** [plessl/wkpdf#28]
I have a bunch of pages that take a long time to load data (10-15 seconds).  

As is, wkpdf appears to render the pdf while a couple of the graphs are still rendering, and so those graphs are not complete.  They are shows as graphs where the line is just starting to be rendered.

I'm running MacOS X Lion 10.7.3 on a MacBook Pro.  

I tried to use the --save-delay <seconds> option and it doesn't appear to add any delay to rendering.  Also, when I run --debug there is no delay before the exit.  I would have guessed that --save-delay would allow the page to finish rendering before starting the pdf.  But it appears to make no difference.  (A really bad workaround is to keep rendering additional random graphs and then hide them at the end, giving wkpdf extra time to complete the original graphs.)

Same behavior every time.

**Comment by plessl** [comment]
Closed by 1d7ffc9b8d0c1f0e24745078cef08c0e23621dfd
