### ISSUE TITLE
How to build wkpdf?

### ISSUE THREAD

**Issue by slessard** [plessl/wkpdf#32]
I'm new to Ruby, but not new to programming. I cloned the repo on my Mac (OS X 10.8.2). I have rubygems, rake, and jeweler installed. Running 'rake gemspec' succeeds, but running 'rake' fails with the message "Don't know how to build task 'default'." How do I actually build wkpdf?

**Comment by plessl** [comment]
Why do you want to build wkpdf? If you just want to use wkpdf there is no need to build a wkpdf gem yourself. You can just install from rubygems (see http://plessl.github.com/wkpdf/).

If you plan to use a modified wkpdf version you have two options. You can either just run wkpdf with the full path to the the working directory (`/home/Users/where/wkpdf/lives/bin/wkpdf --source .. --output`). Or you can build and install a gem for wkpdf yourself using these steps:

```
rake gemspec
rake build
rake install
```

Some more information can be found in the HOW_TO_RELEASE.txt file.

**Comment by slessard** [comment]
I wanted to build it because I fixed a minor issue with page sizes. I've got it build and installed locally now. I'll be sending a pull request as soon as my change shows up in the github web site.  Thanks
