### ISSUE TITLE
wkpdf crashs when running in sandbox

### ISSUE THREAD

**Issue by tobium** [plessl/wkpdf#33]
wpdf does not work in a sandbox.

**Comment by plessl** [comment]
I'm not sure how and whether this can be fixed because I'm not familiar with the sandboxing features of OS X so far. Can you explain how to reproduce this problem?

**Comment by tobium** [comment]
I just call the following in sandboxed mac app: wkpdf --print-background yes --paginate yes --source %s --output %s with NSTask...

**Comment by tobium** [comment]
Process:         wkpdf [1549]
Path:            /Users/_/Documents/_/EverDump.app/Contents/Java/wkpdf
Identifier:      wkpdf
Version:         ???
Code Type:       X86 (Native)
Parent Process:  EverDump [1546]
User ID:         502

Date/Time:       2012-10-07 01:04:18.962 +0200
OS Version:      Mac OS X 10.8.2 (12C54)
Report Version:  10

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x0000000000000000

Application Specific Information:
dyld: launch, running initializers
/usr/lib/libSystem.B.dylib
Bug in libxpc: Domain bootstrapper failed to respond. It is likely crashing in a loop.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libxpc.dylib                    0x9181617d _xpc_runtime_init_once + 1102
1   libdispatch.dylib               0x9102cbf1 dispatch_once_f + 57
2   libxpc.dylib                    0x9180c641 _xpc_runtime_set_domain + 218
3   libxpc.dylib                    0x9180ba39 _libxpc_initializer + 529
4   libSystem.B.dylib               0x98dd9c30 libSystem_initializer + 152
5   dyld                            0x8fed6cda ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 230
6   dyld                            0x8fed6fde ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 64
7   dyld                            0x8fed3268 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) + 356
8   dyld                            0x8fed31cc ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) + 200
9   dyld                            0x8fed31cc ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) + 200
10  dyld                            0x8fed31cc ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) + 200
11  dyld                            0x8fed31cc ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) + 200
12  dyld                            0x8fed31cc ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) + 200
13  dyld                            0x8fed30ba ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 62
14  dyld                            0x8fec4e05 dyld::initializeMainExecutable() + 211
15  dyld                            0x8fec8adb dyld::_main(macho_header const_, unsigned long, int, char const__, char const__, char const__, unsigned long_) + 3050
16  dyld                            0x8fec4376 dyldbootstrap::start(macho_header const_, int, char const__, long, macho_header const_, unsigned long*) + 704
17  dyld                            0x8fec4077 _dyld_start + 71

Thread 0 crashed with X86 Thread State (32-bit):
  eax: 0xac1a4240  ebx: 0xbfffd468  ecx: 0x91824087  edx: 0x000f4540
  edi: 0x91815d40  esi: 0x00000000  ebp: 0xbfffe2c8  esp: 0xbfffd430
   ss: 0x00000023  efl: 0x00010202  eip: 0x9181617d   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x0160a020
Logical CPU: 1

Binary Images:
    0x1000 -     0x5ff7 +wkpdf (???) <1F45A12F-6D79-B168-E19F-C162CC0215F7> /Users/_/Documents/_/EverDump.app/Contents/Java/wkpdf
    0xd000 -   0x12bff3  com.apple.WebKit (8536 - 8536.26.14) <C98F734D-D579-3F89-9A58-9EE890B1748E> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
  0x1dc000 -   0xe6bff3  com.apple.WebCore (8536 - 8536.26.14) <82E97E6B-3F31-39A7-B41F-CD308E6EF238> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore
0x8fec3000 - 0x8fef5e57  dyld (210.2.3) <23516BE4-29BE-350C-91C9-F36E7999F0F1> /usr/lib/dyld
0x90007000 - 0x900dbfff  com.apple.backup.framework (1.4.1 - 1.4.1) <55F2A679-9B21-3F43-A580-4C2ECF6A5FC5> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup

**Comment by plessl** [comment]
Doesn't this look like an XPC bug? Is there any reason why you do not trust the error message `Bug in libxpc: Domain bootstrapper failed to respond. It is likely crashing in a loop.` that is reported in the crash dump.

**Comment by plessl** [comment]
I appreciate your interest in wkpdf.

Unfortunately I have to inform you that changes in OS X made it difficult for me to provide the installation and usage experience, which I envisioned for wkpdf. Hence, I have stopped the development of the rubygems version of wkpdf in December 2014. 

More details on the reasons and some words on how you could contribute to a reincarnation of wkpdf can be found here:

http://plessl.github.io/wkpdf/

Cheers,
 Christian
