### ISSUE TITLE
Source file from disk

### ISSUE THREAD

**Issue by mrtoner** [plessl/wkpdf#37]
I'm perhaps doing this all wrong. Although I've been successful in using a URL from the 'net as a source, I'm utterly failing at using a file from disk. Although _file_ is a supported protocol, I get nothing output:

```
prime-directive:~ don$ wkpdf --source file:index.html --output index.pdf
prime-directive:~ don$ wkpdf --source file:/index.html --output index.pdf
prime-directive:~ don$ wkpdf --source file://index.html --output index.pdf
prime-directive:~ don$ wkpdf --source file:///index.html --output index.pdf
```

(I thought the last command was the correct one, but I tried the others as well.)

I'm using version 0.6.9 on OSX 10.8.2 -- is it possible that the _file_ protocol is broken?

**Comment by plessl** [comment]
No need for the `file://` protocol, the following should just work: `wkpdf --source index.html --output index.pdf`

If you prefer the file protocol, you need to use absolute paths `file:///Users/bla/path/to/index.html`

**Comment by mrtoner** [comment]
Yes, I'd tried both of those options just in case:

```
prime-directive:~ don$ wkpdf --source index.html --output index.pdf
Could not load resource 1, error: The requested URL was not found on this server.
prime-directive:~ don$ wkpdf --source /Users/don/index.html --output index.pdf
Could not load resource 1, error: The requested URL was not found on this server.
prime-directive:~ don$ wkpdf --source file:///Users/don/index.html --output index.pdf
Could not load resource 1, error: The requested URL was not found on this server.
prime-directive:~ don$ ls
Desktop     Downloads   Library     Music       Public      index.html
Documents   Dropbox     Movies      Pictures    Slogger     wkpdf.css
```

**Comment by plessl** [comment]
The error does not refer to the file index.html but to a resource you are using in your HTML file, e.g. an image.

**Comment by mrtoner** [comment]
Exactly so. Thanks!
