### ISSUE TITLE
Shrink to fit

### ISSUE THREAD

**Issue by mrtoner** [plessl/wkpdf#39]
Okay, last issue for today, actually a feature request. Unless it's already possible to do this, I'd like to see an option to reduce the horizontal width of the page to fit the selected paper size. Right now, I'm seeing web sites that are wider than letter-sized being cut off on the right edge. This can be mitigated by using a larger paper size, but that creates so very large margins.

(Perhaps a user stylesheet could also fix this, but as of yet I've not been able to get that flag to work.)

**Comment by plessl** [comment]
Have you tried the option `--paginate no`?

**Comment by mrtoner** [comment]
Yes. And now that I'm trying this with a sufficiently long page, I'm finding that `--paginate no` doesn't work, either:

```
wkpdf --source http://plessl.github.com/wkpdf --paginate no --stylesheet-media screen --print-background yes --output test.pdf
```

![Screenshot of Finder](https://f.cloud.github.com/assets/1012776/98886/a1da5c0c-6739-11e2-9168-2b5d5ee1d6e5.png)

**Comment by mrtoner** [comment]
Any further thoughts on this?

**Comment by plessl** [comment]
On my machine `--paginate no` works just fine, see attached image. If pagination is disabled no pages should be generated, regardless of the height.

Can you double check whether you can reproduce the problem?

![test](https://f.cloud.github.com/assets/25529/148061/212b5f54-74ed-11e2-8d83-99de53d2a84a.png)

**Comment by mrtoner** [comment]
Nope, neither `--paginate no` nor `-a no` are working on my machine (Mac Mini 2011, OS X 10.8.2). However, `--no-paginate` **does** work -- and it appears to eliminate the right side cut off.

There are some color variations when tested against http://apple.com (in the top nav bar and a couple of other places), but overall a very nice reproduction of a web page.

**Comment by plessl** [comment]
Regarding the colors, etc: wkpdf uses the WebKit framework for HTML rendering. That is, it should behave exactly like Safari when "printing to PDF". If I print the Apple webpage to PDF from Safari, the same odd yellow borders appear at the edges of the boxes that have nice gradients and shadows on screen. Thus there is nothing I can do about it. It is probably a problem with the CSS stylesheet for printing.

I have no clue however, why wkpdf does not interpret --paginate correctly on your machine. Can you make sure that you are running the latest version of wkpdf (0.6.10) and that you have installed via Rubgems in a default OS X Ruby installation (i.e. no rvm or similar?

**Comment by mrtoner** [comment]
No worries about the colors. I did attempt to update wkpdf last night before testing again, but I **am** running 0.6.10.  I did install via your instructions and I believe this is a default install of Ruby (since I don't play with it much).

Since `--no-paginate` is working I'm satisfied, but if there's anything I can do to help you debug `--paginate no` just let me know.

**Comment by plessl** [comment]
Last guess: what shell are you using? bash?

**Comment by mrtoner** [comment]
Yes, bash.

**Comment by plessl** [comment]
Hmm, I'm running out of ideas. I will close this issue until there is a way to reproduce this behavior on my setup.
