### ISSUE TITLE
generate PDFs with outlines/bookmarks

### ISSUE THREAD

**Issue by devietti** [plessl/wkpdf#40]
It would be great if the generated PDFs included outline/bookmark information (as in other html-to-pdf generation tools like [1]).  The outline is typically auto-generated from the <h1>...<h5> tags in the HTML document.  I don't know if WebKit supports this natively.

[1] https://github.com/chrisglass/xhtml2pdf/blob/master/doc/usage.rst#outlines-bookmarks

**Comment by plessl** [comment]
I appreciate your interest in wkpdf.

Unfortunately I have to inform you that changes in OS X made it difficult for me to provide the installation and usage experience, which I envisioned for wkpdf. Hence, I have stopped the development of the rubygems version of wkpdf in December 2014. 

More details on the reasons and some words on how you could contribute to a reincarnation of wkpdf can be found here:

http://plessl.github.io/wkpdf/

Cheers,
 Christian
