### ISSUE TITLE
Error when using an user script

### ISSUE THREAD

**Issue by tiojoca** [plessl/wkpdf#42]
When an user script url is passed as an argument to wkpdf the pdf generation is failing and the following error is returned:

```
Controller#webView_didFinishLoadForFrame: OSX::OCException: NSInvalidArgumentException - -[NSURL length]: unrecognized selector sent to instance
    /System/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_wrapper.rb:50:in `ocm_send'
    /System/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_wrapper.rb:50:in `method_missing'
    /Library/Ruby/Gems/1.8/gems/wkpdf-0.6.10-universal-darwin/bin/../lib/controller.rb:186:in `loadUserScript
(...)
```

Upon code inspection, it seems the error's on `controller.rb` in the `loadUserScript` method when it expects the `location` argument to be a string, which it then tries to converts to an `NSURL` but apparently the argument's already being sent as an `NSURL`. I've changed the line

``` ruby
theURL = NSURL.URLWithString(location)
```

to

``` ruby
theURL = location
```

on my local version of wkpdf and the pdf generation with user script seems to go fine.

**Comment by plessl** [comment]
Thanks for the report. I have just released an updated version 0.6.11 of wkpdf, that fixes the problem with user scripts.
