### ISSUE TITLE
Nice ! How about Homebrew formula ?

### ISSUE THREAD

**Issue by mderazon** [plessl/wkpdf#46]

**Comment by michahell** [comment]
aaaaaaaand theeeeeen? a homebrew formula would we awesome sir!

**Comment by plessl** [comment]
I appreciate your interest in wkpdf.

Unfortunately I have to inform you that changes in OS X made it difficult for me to provide the installation and usage experience, which I envisioned for wkpdf. Hence, I have stopped the development of the rubygems version of wkpdf in December 2014. 

More details on the reasons and some words on how you could contribute to a reincarnation of wkpdf can be found here:

http://plessl.github.io/wkpdf/

Cheers,
 Christian
