### ISSUE TITLE
nvd3 svg charts with wkhtmltoimage

### ISSUE THREAD

**Issue by tylik1** [plessl/wkpdf#47]
Sorry this is probably offtopic but I couldn't find any info on this. I made a couple of graphs with nvd3 js library. Basically it uses svg to create charts. But I couldn't generate images using wkhtmltoimage. Although it partly works as I'm able to see text ouput from the graph which is also generated with svg.
I've included Function.prototype.bind which should have solved bugs with svg, and I've also tried flag --debug-javascript which showed no errors. Javascript delay was set to 5 seconds (--javascript-delay 5000)
Probably someone already had such problems. Thanks.

**Comment by plessl** [comment]
Yes, this is off topic. wkhtmltoimage is a different tool than wkpdf. I have no idea about wkhtmltoimage
