### ISSUE TITLE
Why can't I install this???

### ISSUE THREAD

**Issue by PacoH** [plessl/wkpdf#49]
I tried the following as per instructions at https://plessl.github.io/wkpdf/:

`user$ sudo gem update --system`

```
…
Successfully installed rubygems-update-2.4.1
…
```

`user$ sudo gem install wkpdf`

```
Password:
ERROR:  Could not find a valid gem 'wkpdf' (>= 0) in any repository
ERROR:  Possible alternatives: wkpdf
```

Checked status:

`http://status.rubygems.org/`

```
RubyGems.org Status: UP
```

Tried:

`user$ sudo traceroute rubygems.org`

```
Never completed.
```

`user$ ping rubygems.org`

```
PING rubygems.org (54.186.104.15): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
```

`user$ gem list -r`

```
…
wkhtmltopdf (0.1.2)
…
wkpdf (0.6.11 universal-darwin)
```

Tried:

```
user$ sudo gem install wkpdf -s http://production.cf.rubygems.org/

    Password:
    ERROR:  Could not find a valid gem 'wkpdf' (>= 0) in any repository
    ERROR:  Possible alternatives: wkpdf
```

Nothing worked, yet I was able to install `wkhtmltopdf` without incident.

Now what?

**Comment by plessl** [comment]
Just to check: You are using Mac OS X, correct?

**Comment by PacoH** [comment]
Thanks for the swift reply. I am using OS X 10.8.5.

**Comment by plessl** [comment]
And does 'gem source' report 'https://rubygems.org' as a source?

**Comment by PacoH** [comment]
Yes.
    user$ gem source
    **\* CURRENT SOURCES ***

```
https://rubygems.org/
```

**Comment by plessl** [comment]
I have currently no idea, what could cause this problem. I can't reproduce the problem myself, but somebody also just reported the same problem just today. Maybe it's an intermittent problem with rubygems.org?

**Comment by PacoH** [comment]
Yes, well that's why I tried using http://production.cf.rubygems.org/ as suggested in a forum post of someone having a similar problem with another package. The OP was able to eventually install it at a later time so I will just wait and try later. Thanks for your help. I'll report back if I succeed.

**Comment by plessl** [comment]
I appreciate your interest in wkpdf.

Unfortunately I have to inform you that changes in OS X made it difficult for me to provide the installation and usage experience, which I envisioned for wkpdf. Hence, I have stopped the development of the rubygems version of wkpdf in December 2014. 

More details on the reasons and some words on how you could contribute to a reincarnation of wkpdf can be found here:

http://plessl.github.io/wkpdf/

Cheers,
 Christian
