### ISSUE TITLE
 `require': cannot load such file -- rdoc/usage (LoadError)

### ISSUE THREAD

**Issue by CodeBrauer** [plessl/wkpdf#50]
`CodeBrauer:Desktop gabriel$ wkpdf --source http://www.apple.com --output apple.pdf`

**Output**

``` bash
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rdoc/usage (LoadError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/wkpdf-0.6.11-universal-darwin/lib/commandline_parser.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/wkpdf-0.6.11-universal-darwin/lib/wkpdf.rb:14:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/wkpdf-0.6.11-universal-darwin/bin/wkpdf:4:in `<top (required)>'
    from /usr/bin/wkpdf:23:in `load'
    from /usr/bin/wkpdf:23:in `<main>'
```

Installed RubyCocoa 1.2.0

Mac OS 10.10.1
Ruby: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by plandem** [comment]
same. osx 10.10 too

**Comment by plessl** [comment]
I appreciate your interest in wkpdf. Changes in OS X made it difficult for me to provide the installation and usage experience, which I envisioned for wkpdf. Hence, I have stopped the development of the rubygems version of wkpdf in December 2014. 

More details on the reasons and some words on how you could contribute to a reincarnation of wkpdf can be found here:

http://plessl.github.io/wkpdf/

Cheers,
 Christian
